db:
  dsn: "root:root@tcp(localhost:13316)/webook"
redis:
  addr: "localhost:6379"
kafka:
  addrs:
    - "localhost:9094"
grpc:
  server:
    port: 8090
    etcdAddrs:
      - "localhost:12379"
