# pvc => PersistentVolumeClaim
# 开始描述 mysql 需要的存储资源的特征
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # 这个是指我 MySQL 要用的东西
  # 我 k8s 有什么
  name: webook-mysql-claim
spec:
  # 这里的 manual 其实是一个我们自己写的，只是用来维护
  storageClassName: manual
  # 访问模式，这里是控制能不能被多个 pod 读写
  accessModes:
    - ReadWriteOnce
  # 究竟需要一些什么资源
  resources:
    requests:
      # 需要一个 G 的容量
      storage: 512Mi