// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	repository3 "github.com/TengFeiyang01/webook/webook/article/repository"
	cache3 "github.com/TengFeiyang01/webook/webook/article/repository/cache"
	dao3 "github.com/TengFeiyang01/webook/webook/article/repository/dao"
	service3 "github.com/TengFeiyang01/webook/webook/article/service"
	repository2 "github.com/TengFeiyang01/webook/webook/interactive/repository"
	cache2 "github.com/TengFeiyang01/webook/webook/interactive/repository/cache"
	dao2 "github.com/TengFeiyang01/webook/webook/interactive/repository/dao"
	service2 "github.com/TengFeiyang01/webook/webook/interactive/service"
	"github.com/TengFeiyang01/webook/webook/internal/repository"
	"github.com/TengFeiyang01/webook/webook/internal/repository/cache"
	"github.com/TengFeiyang01/webook/webook/internal/repository/dao"
	"github.com/TengFeiyang01/webook/webook/internal/service"
	"github.com/TengFeiyang01/webook/webook/internal/web"
	"github.com/TengFeiyang01/webook/webook/internal/web/jwt"
	"github.com/TengFeiyang01/webook/webook/ioc"
	"github.com/google/wire"
)

import (
	_ "github.com/spf13/viper/remote"
)

// Injectors from wire.go:

func InitApp() *App {
	cmdable := ioc.InitRedis()
	handler := jwt.NewRedisJWT(cmdable)
	loggerV1 := ioc.InitLogger()
	v := ioc.InitGinMiddlewares(cmdable, handler, loggerV1)
	db := ioc.InitDB(loggerV1)
	userDAO := dao.NewUserDAO(db)
	userCache := cache.NewRedisUserCache(cmdable)
	userRepository := repository.NewUserRepository(userDAO, userCache)
	userService := service.NewUserService(userRepository, loggerV1)
	codeCache := cache.NewRedisCodeCache(cmdable)
	codeRepository := repository.NewCodeRepository(codeCache)
	smsService := ioc.InitSMSService(cmdable)
	codeService := service.NewCodeService(codeRepository, smsService)
	userHandler := web.NewUserHandler(userService, codeService, cmdable, handler, loggerV1)
	wechatService := ioc.InitOAuth2WechatService(loggerV1)
	wechatHandlerConfig := ioc.NewWechatHandlerConfig()
	oAuth2WechatHandler := web.NewOAuth2WechatHandler(wechatService, userService, wechatHandlerConfig, handler)
	client := ioc.InitEtcd()
	articleServiceClient := ioc.InitArtGRPCClientV1(client)
	interactiveServiceClient := ioc.InitIntrGRPCClientV1(client)
	articleHandler := web.NewArticleHandler(articleServiceClient, loggerV1, interactiveServiceClient)
	engine := ioc.InitWebServer(v, userHandler, oAuth2WechatHandler, articleHandler)
	v2 := ioc.NewConsumers()
	rankingService := service.NewBatchRankingService(articleServiceClient, interactiveServiceClient)
	rlockClient := ioc.InitRLockClient(cmdable)
	rankingJob := ioc.InitRankingJob(rankingService, loggerV1, rlockClient)
	cron := ioc.InitJobs(loggerV1, rankingJob)
	app := &App{
		Server:    engine,
		Consumers: v2,
		cron:      cron,
	}
	return app
}

// wire.go:

var interactiveSvcSet = wire.NewSet(dao2.NewGORMInteractiveDAO, cache2.NewInteractiveRedisCache, repository2.NewCachedInteractiveRepository, service2.NewInteractiveService)

var articleSvcSet = wire.NewSet(cache3.NewArticleCache, repository3.NewCachedArticleRepository, service3.NewArticleService, dao3.NewGORMArticleDAO)

var rankingServiceSet = wire.NewSet(repository.NewCachedRankingRepository, cache.NewRankingRedisCache, service.NewBatchRankingService)
