---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by tengfei.yang.
--- DateTime: 2024/8/23 9:14
---
wrk.method="POST"
wrk.headers["Content-Type"] = "application/json"
-- 这个要改为你的注册的数据
wrk.body='{"email":"2196442691@qq.com", "password": "123#@qqcom"}'