apiVersion: batch/v1
kind: CronJob
metadata:
  name: demojob
spec:
  schedule: "* * * * *" #	Run every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: demojob
              image: sparrow/demojob:v0.0.1
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure