db:
  dsn: "root:root@tcp(localhost:13316)/webook"
redis:
  addr: "localhost:6379"
kafka:
  addrs:
    - "localhost:9094"

etcd:
  endpoints:
    - "localhost:12379"

grpc:
  client:
    intr:
      name: "interactive"
      secure: false
    art:
      name: "article"
      secure: false

#grpc:
#  client:
#    intr:
#      addr: "localhost:8090"
#      secure: false
#      threshold: 100
#    art:
#      addr: "localhost:8091"
#      secure: false
#      threshold: 100